/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsIdSettingsRouteImport } from './routes/projects/$id/settings'
import { Route as ProjectsIdInstallRouteImport } from './routes/projects/$id/install'
import { Route as ProjectsIdInboxRouteImport } from './routes/projects/$id/inbox'
import { Route as ApiWidgetPinsRouteImport } from './routes/api/widget/pins'
import { Route as ApiWidgetInitRouteImport } from './routes/api/widget/init'
import { Route as ApiWidgetEventsRouteImport } from './routes/api/widget/events'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiAuthSendMagicLinkRouteImport } from './routes/api/auth/send-magic-link'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ProjectsIdPinsPinIdRouteImport } from './routes/projects/$id/pins/$pinId'
import { Route as ApiWidgetPinsPinIdRouteImport } from './routes/api/widget/pins/$pinId'
import { Route as ApiScreenshotsProjectKeyPinIdRouteImport } from './routes/api/screenshots/$projectKey/$pinId'
import { Route as ApiProjectsIdEventsRouteImport } from './routes/api/projects/$id/events'
import { Route as ApiWidgetPinsPinIdRepliesRouteImport } from './routes/api/widget/pins/$pinId/replies'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSettingsRoute = ProjectsIdSettingsRouteImport.update({
  id: '/projects/$id/settings',
  path: '/projects/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdInstallRoute = ProjectsIdInstallRouteImport.update({
  id: '/projects/$id/install',
  path: '/projects/$id/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdInboxRoute = ProjectsIdInboxRouteImport.update({
  id: '/projects/$id/inbox',
  path: '/projects/$id/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetPinsRoute = ApiWidgetPinsRouteImport.update({
  id: '/api/widget/pins',
  path: '/api/widget/pins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetInitRoute = ApiWidgetInitRouteImport.update({
  id: '/api/widget/init',
  path: '/api/widget/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetEventsRoute = ApiWidgetEventsRouteImport.update({
  id: '/api/widget/events',
  path: '/api/widget/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendMagicLinkRoute = ApiAuthSendMagicLinkRouteImport.update({
  id: '/api/auth/send-magic-link',
  path: '/api/auth/send-magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdPinsPinIdRoute = ProjectsIdPinsPinIdRouteImport.update({
  id: '/projects/$id/pins/$pinId',
  path: '/projects/$id/pins/$pinId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetPinsPinIdRoute = ApiWidgetPinsPinIdRouteImport.update({
  id: '/$pinId',
  path: '/$pinId',
  getParentRoute: () => ApiWidgetPinsRoute,
} as any)
const ApiScreenshotsProjectKeyPinIdRoute =
  ApiScreenshotsProjectKeyPinIdRouteImport.update({
    id: '/api/screenshots/$projectKey/$pinId',
    path: '/api/screenshots/$projectKey/$pinId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsIdEventsRoute = ApiProjectsIdEventsRouteImport.update({
  id: '/api/projects/$id/events',
  path: '/api/projects/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetPinsPinIdRepliesRoute =
  ApiWidgetPinsPinIdRepliesRouteImport.update({
    id: '/replies',
    path: '/replies',
    getParentRoute: () => ApiWidgetPinsPinIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/send-magic-link': typeof ApiAuthSendMagicLinkRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/widget/events': typeof ApiWidgetEventsRoute
  '/api/widget/init': typeof ApiWidgetInitRoute
  '/api/widget/pins': typeof ApiWidgetPinsRouteWithChildren
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/install': typeof ProjectsIdInstallRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/api/projects/$id/events': typeof ApiProjectsIdEventsRoute
  '/api/screenshots/$projectKey/$pinId': typeof ApiScreenshotsProjectKeyPinIdRoute
  '/api/widget/pins/$pinId': typeof ApiWidgetPinsPinIdRouteWithChildren
  '/projects/$id/pins/$pinId': typeof ProjectsIdPinsPinIdRoute
  '/api/widget/pins/$pinId/replies': typeof ApiWidgetPinsPinIdRepliesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/send-magic-link': typeof ApiAuthSendMagicLinkRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/widget/events': typeof ApiWidgetEventsRoute
  '/api/widget/init': typeof ApiWidgetInitRoute
  '/api/widget/pins': typeof ApiWidgetPinsRouteWithChildren
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/install': typeof ProjectsIdInstallRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/api/projects/$id/events': typeof ApiProjectsIdEventsRoute
  '/api/screenshots/$projectKey/$pinId': typeof ApiScreenshotsProjectKeyPinIdRoute
  '/api/widget/pins/$pinId': typeof ApiWidgetPinsPinIdRouteWithChildren
  '/projects/$id/pins/$pinId': typeof ProjectsIdPinsPinIdRoute
  '/api/widget/pins/$pinId/replies': typeof ApiWidgetPinsPinIdRepliesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/send-magic-link': typeof ApiAuthSendMagicLinkRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/widget/events': typeof ApiWidgetEventsRoute
  '/api/widget/init': typeof ApiWidgetInitRoute
  '/api/widget/pins': typeof ApiWidgetPinsRouteWithChildren
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/install': typeof ProjectsIdInstallRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/api/projects/$id/events': typeof ApiProjectsIdEventsRoute
  '/api/screenshots/$projectKey/$pinId': typeof ApiScreenshotsProjectKeyPinIdRoute
  '/api/widget/pins/$pinId': typeof ApiWidgetPinsPinIdRouteWithChildren
  '/projects/$id/pins/$pinId': typeof ProjectsIdPinsPinIdRoute
  '/api/widget/pins/$pinId/replies': typeof ApiWidgetPinsPinIdRepliesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/projects/new'
    | '/projects/'
    | '/api/auth/logout'
    | '/api/auth/send-magic-link'
    | '/api/auth/verify'
    | '/api/widget/events'
    | '/api/widget/init'
    | '/api/widget/pins'
    | '/projects/$id/inbox'
    | '/projects/$id/install'
    | '/projects/$id/settings'
    | '/api/projects/$id/events'
    | '/api/screenshots/$projectKey/$pinId'
    | '/api/widget/pins/$pinId'
    | '/projects/$id/pins/$pinId'
    | '/api/widget/pins/$pinId/replies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/projects/new'
    | '/projects'
    | '/api/auth/logout'
    | '/api/auth/send-magic-link'
    | '/api/auth/verify'
    | '/api/widget/events'
    | '/api/widget/init'
    | '/api/widget/pins'
    | '/projects/$id/inbox'
    | '/projects/$id/install'
    | '/projects/$id/settings'
    | '/api/projects/$id/events'
    | '/api/screenshots/$projectKey/$pinId'
    | '/api/widget/pins/$pinId'
    | '/projects/$id/pins/$pinId'
    | '/api/widget/pins/$pinId/replies'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/projects/new'
    | '/projects/'
    | '/api/auth/logout'
    | '/api/auth/send-magic-link'
    | '/api/auth/verify'
    | '/api/widget/events'
    | '/api/widget/init'
    | '/api/widget/pins'
    | '/projects/$id/inbox'
    | '/projects/$id/install'
    | '/projects/$id/settings'
    | '/api/projects/$id/events'
    | '/api/screenshots/$projectKey/$pinId'
    | '/api/widget/pins/$pinId'
    | '/projects/$id/pins/$pinId'
    | '/api/widget/pins/$pinId/replies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSendMagicLinkRoute: typeof ApiAuthSendMagicLinkRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiWidgetEventsRoute: typeof ApiWidgetEventsRoute
  ApiWidgetInitRoute: typeof ApiWidgetInitRoute
  ApiWidgetPinsRoute: typeof ApiWidgetPinsRouteWithChildren
  ProjectsIdInboxRoute: typeof ProjectsIdInboxRoute
  ProjectsIdInstallRoute: typeof ProjectsIdInstallRoute
  ProjectsIdSettingsRoute: typeof ProjectsIdSettingsRoute
  ApiProjectsIdEventsRoute: typeof ApiProjectsIdEventsRoute
  ApiScreenshotsProjectKeyPinIdRoute: typeof ApiScreenshotsProjectKeyPinIdRoute
  ProjectsIdPinsPinIdRoute: typeof ProjectsIdPinsPinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/settings': {
      id: '/projects/$id/settings'
      path: '/projects/$id/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof ProjectsIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/install': {
      id: '/projects/$id/install'
      path: '/projects/$id/install'
      fullPath: '/projects/$id/install'
      preLoaderRoute: typeof ProjectsIdInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/inbox': {
      id: '/projects/$id/inbox'
      path: '/projects/$id/inbox'
      fullPath: '/projects/$id/inbox'
      preLoaderRoute: typeof ProjectsIdInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/pins': {
      id: '/api/widget/pins'
      path: '/api/widget/pins'
      fullPath: '/api/widget/pins'
      preLoaderRoute: typeof ApiWidgetPinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/init': {
      id: '/api/widget/init'
      path: '/api/widget/init'
      fullPath: '/api/widget/init'
      preLoaderRoute: typeof ApiWidgetInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/events': {
      id: '/api/widget/events'
      path: '/api/widget/events'
      fullPath: '/api/widget/events'
      preLoaderRoute: typeof ApiWidgetEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-magic-link': {
      id: '/api/auth/send-magic-link'
      path: '/api/auth/send-magic-link'
      fullPath: '/api/auth/send-magic-link'
      preLoaderRoute: typeof ApiAuthSendMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/pins/$pinId': {
      id: '/projects/$id/pins/$pinId'
      path: '/projects/$id/pins/$pinId'
      fullPath: '/projects/$id/pins/$pinId'
      preLoaderRoute: typeof ProjectsIdPinsPinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/pins/$pinId': {
      id: '/api/widget/pins/$pinId'
      path: '/$pinId'
      fullPath: '/api/widget/pins/$pinId'
      preLoaderRoute: typeof ApiWidgetPinsPinIdRouteImport
      parentRoute: typeof ApiWidgetPinsRoute
    }
    '/api/screenshots/$projectKey/$pinId': {
      id: '/api/screenshots/$projectKey/$pinId'
      path: '/api/screenshots/$projectKey/$pinId'
      fullPath: '/api/screenshots/$projectKey/$pinId'
      preLoaderRoute: typeof ApiScreenshotsProjectKeyPinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/events': {
      id: '/api/projects/$id/events'
      path: '/api/projects/$id/events'
      fullPath: '/api/projects/$id/events'
      preLoaderRoute: typeof ApiProjectsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/pins/$pinId/replies': {
      id: '/api/widget/pins/$pinId/replies'
      path: '/replies'
      fullPath: '/api/widget/pins/$pinId/replies'
      preLoaderRoute: typeof ApiWidgetPinsPinIdRepliesRouteImport
      parentRoute: typeof ApiWidgetPinsPinIdRoute
    }
  }
}

interface ApiWidgetPinsPinIdRouteChildren {
  ApiWidgetPinsPinIdRepliesRoute: typeof ApiWidgetPinsPinIdRepliesRoute
}

const ApiWidgetPinsPinIdRouteChildren: ApiWidgetPinsPinIdRouteChildren = {
  ApiWidgetPinsPinIdRepliesRoute: ApiWidgetPinsPinIdRepliesRoute,
}

const ApiWidgetPinsPinIdRouteWithChildren =
  ApiWidgetPinsPinIdRoute._addFileChildren(ApiWidgetPinsPinIdRouteChildren)

interface ApiWidgetPinsRouteChildren {
  ApiWidgetPinsPinIdRoute: typeof ApiWidgetPinsPinIdRouteWithChildren
}

const ApiWidgetPinsRouteChildren: ApiWidgetPinsRouteChildren = {
  ApiWidgetPinsPinIdRoute: ApiWidgetPinsPinIdRouteWithChildren,
}

const ApiWidgetPinsRouteWithChildren = ApiWidgetPinsRoute._addFileChildren(
  ApiWidgetPinsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSendMagicLinkRoute: ApiAuthSendMagicLinkRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiWidgetEventsRoute: ApiWidgetEventsRoute,
  ApiWidgetInitRoute: ApiWidgetInitRoute,
  ApiWidgetPinsRoute: ApiWidgetPinsRouteWithChildren,
  ProjectsIdInboxRoute: ProjectsIdInboxRoute,
  ProjectsIdInstallRoute: ProjectsIdInstallRoute,
  ProjectsIdSettingsRoute: ProjectsIdSettingsRoute,
  ApiProjectsIdEventsRoute: ApiProjectsIdEventsRoute,
  ApiScreenshotsProjectKeyPinIdRoute: ApiScreenshotsProjectKeyPinIdRoute,
  ProjectsIdPinsPinIdRoute: ProjectsIdPinsPinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
